apiVersion: v1
kind: Namespace
metadata:
  name: asdasdasd-dev
  labels:
    environment-id: env_869d8bc5-9512-456c-82d0-70226aed5ca6
    project-id: project_1ef89839-ad9b-4bbd-b180-b674caa0eeb0
    project-name: NewProjectEnvTesting2
    environment-name: dev
    organization-id: org_6a50eae7-e490-4569-be36-6e9e2cec1ffe
